### PR TITLE
Anya/experience card backend

### PR DESCRIPTION
**Pull request by awesomeann**
## Describe your changes

1. Creted Experiences Model 
2. Created relationships between Experience and Profile models
3. Created serializers for Experience
4. Updated Profile Detail Serialaizer to include the list of experiences
5. Created new permissions rule that you can only modify the experience if you are the owner of the profile associated with the Experience.

Test Screenshots:
**GET**

image

**POST**

image

image

**PUT**

image
image
image

**DELETE**

image
image

**Trying to update an experience for a non-existent profile**

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## What kind of feedback do you need?

E.g. Do you need a quick look or a thorough assessment?

## Checklist:

- [X] I have performed a self-review of my code
- [X] I have recommended where to start and how to proceed with the review

### CODE REVIEW

**Review by shayzimm — APPROVED** [review]

**Review by blakerach1 — CHANGES_REQUESTED** [review]
Hey Anya, the start_date and end_date don't appear to be populating correctly with user's input.

**Comment by blakerach1** [comment]
Also, I think the insomnia screenshots are duplicated in some places and missing the correct screenshots of the tests that you've performed.

**Comment by awesomeann** [comment]
> Hey Anya, the start_date and end_date don't appear to be populating correctly with user's input.

could you please expand on that? I thought we are using  mm/YYYY format

**Comment by awesomeann** [comment]
> Also, I think the insomnia screenshots are duplicated in some places and missing the correct screenshots of the tests that you've performed.

Yep just saw that thank you , updated the description with the correct screenshots

**Comment by blakerach1** [comment]
Hopefully this is replying to your comment above... If you take a look at your screenshot, you will see the input is start_date: 02/2023 and is appearing in the response as 2023-01-01, and the end_date entered as 04/2024 us returning in the response as 2024-01-01. So the user has entered April 2024, but are getting Jan 2024 in the database for example.

**Comment by awesomeann** [comment]
> Hopefully this is replying to your comment above... If you take a look at your screenshot, you will see the input is start_date: 02/2023 and is appearing in the response as 2023-01-01, and the end_date entered as 04/2024 us returning in the response as 2024-01-01. So the user has entered April 2024, but are getting Jan 2024 in the database for example.

Yep I can see that now ! Thanks will check what's going on there

**Comment by awesomeann** [comment]
> Hopefully this is replying to your comment above... If you take a look at your screenshot, you will see the input is start_date: 02/2023 and is appearing in the response as 2023-01-01, and the end_date entered as 04/2024 us returning in the response as 2024-01-01. So the user has entered April 2024, but are getting Jan 2024 in the database for example.

hey Rachel, I tried to change the format of the dates but I couldn't find the solution yet. I have booked a meeting with Laura for tomorrow. For now it is working if I provide the standard date format ("dd-mm-yyyy")- so I was thinking if we could merge it the way it is now and I will create a separate card to change the dates after my 1:1 so that I don't stop anyone depending on this. backend and can start working on other cards.
image

**Review by blakerach1 — APPROVED** [review]

**Pull request merged**
